Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PFinal.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/SOCIOSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PFinal.Models;

namespace PFinal.Controllers
{
    public class SOCIOSController : Controller
    {
        private PROYECTOEntities db = new PROYECTOEntities();

        // GET: SOCIOS
        public ActionResult Index()
        {
            return View(db.SOCIOS.ToList());
        }

        // GET: SOCIOS/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // GET: SOCIOS/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SOCIOS/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NOMBRE,APELLIDOS,CEDULA,FOTO,DIRECCION,TELEFONO,SEXO,EDAD,FECHA_NACIMIENTO,DATOS_MEMBRESIA,LUGAR_TRABAJO,DIRECCION_OFICINA,TEL_OFICINA,ESTADO,FECHA_INGRESO,FECHA_SALIDA")] SOCIOS sOCIOS)
        {
            if (ModelState.IsValid)
            {
                db.SOCIOS.Add(sOCIOS);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sOCIOS);
        }

        // GET: SOCIOS/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // POST: SOCIOS/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NOMBRE,APELLIDOS,CEDULA,FOTO,DIRECCION,TELEFONO,SEXO,EDAD,FECHA_NACIMIENTO,DATOS_MEMBRESIA,LUGAR_TRABAJO,DIRECCION_OFICINA,TEL_OFICINA,ESTADO,FECHA_INGRESO,FECHA_SALIDA")] SOCIOS sOCIOS)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sOCIOS).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sOCIOS);
        }

        // GET: SOCIOS/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            if (sOCIOS == null)
            {
                return HttpNotFound();
            }
            return View(sOCIOS);
        }

        // POST: SOCIOS/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SOCIOS sOCIOS = db.SOCIOS.Find(id);
            db.SOCIOS.Remove(sOCIOS);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/USUARIOsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PFinal.Models;

namespace PFinal.Controllers
{
    public class USUARIOsController : Controller
    {
        private PROYECTOEntities db = new PROYECTOEntities();

        // GET: USUARIOs
        public ActionResult Index()
        {
            return View(db.USUARIO.ToList());
        }

        // GET: USUARIOs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USUARIO uSUARIO = db.USUARIO.Find(id);
            if (uSUARIO == null)
            {
                return HttpNotFound();
            }
            return View(uSUARIO);
        }

        // GET: USUARIOs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: USUARIOs/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NOMBRE,CONTRASEñA")] USUARIO uSUARIO)
        {
            if (ModelState.IsValid)
            {
                db.USUARIO.Add(uSUARIO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uSUARIO);
        }

        // GET: USUARIOs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USUARIO uSUARIO = db.USUARIO.Find(id);
            if (uSUARIO == null)
            {
                return HttpNotFound();
            }
            return View(uSUARIO);
        }

        // POST: USUARIOs/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NOMBRE,CONTRASEñA")] USUARIO uSUARIO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uSUARIO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uSUARIO);
        }

        // GET: USUARIOs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USUARIO uSUARIO = db.USUARIO.Find(id);
            if (uSUARIO == null)
            {
                return HttpNotFound();
            }
            return View(uSUARIO);
        }

        // POST: USUARIOs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            USUARIO uSUARIO = db.USUARIO.Find(id);
            db.USUARIO.Remove(uSUARIO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div id="header-wrapper">
    <div id="header" class="container">
        <div id="logo">
            <h1><a href="#">Proyecto final web</a></h1>
            <span>Design by <a href="" rel="nofollow">TEMPLATED</a></span>
        </div>
        <div id="menu">
            <ul>
                <li class="current_page_item"><a href="#" accesskey="1" title="">Wallner's</a></li>
                <li>@Html.ActionLink("Usuario", "Index", "USUARIOs")<a href="#" accesskey="2" title=""></a></li>
                <li>@Html.ActionLink("Socios", "Index", "SOCIOS")<a href="#" accesskey="3" title=""></a></li>
                <li><a href="#" accesskey="4" title="">Sobre nosotros</a></li>
                <li><a href="#" accesskey="5" title="">Concatos></li>
            </ul>
        </div>
    </div>
</div>
<div id="wrapper2">
    <div id="welcome" class="container">
        <div class="title">
            <h2>Welcome to our website</h2>
        </div>
        <p>This is <strong>MetroBiz</strong>, a free, fully standards-compliant CSS template designed by <a href="http://templated.co" rel="nofollow">TEMPLATED</a>. The photos in this template are from <a href="http://fotogrph.com/"> Fotogrph</a>. This free template is released under the <a href="http://templated.co/license">Creative Commons Attribution</a> license, so you're pretty much free to do whatever you want with it (even use it commercially) provided you give us credit for it. Have fun :) </p>
    </div>
</div>
<div id="wrapper3">
    <div id="three-column" class="container">
        <div><span class="arrow-down"></span></div>
        <div id="tbox1">
            <span class="icon icon-wrench"></span>
            <div class="title">
                <h2>Maecenas luctus</h2>
            </div>
            <p>Nullam non wisi a sem semper eleifend. Donec mattis libero eget urna. Duis pretium velit ac suscipit mauris. Proin eu wisi suscipit nulla suscipit interdum.</p>
            <a href="#" class="button">Learn More</a>
        </div>
        <div id="tbox2">
            <span class="icon icon-cogs"></span>
            <div class="title">
                <h2>Integer gravida</h2>
            </div>
            <p>Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem semper suscipit eleifend. Donec mattis libero eget urna. Duis pretium velit ac mauris.</p>
            <a href="#" class="button">Learn More</a>
        </div>
        <div id="tbox3">
            <span class="icon icon-legal"></span>
            <div class="title">
                <h2>Praesent mauris</h2>
            </div>
            <p>Donec mattis libero eget urna. Duis pretium velit ac mauris. Proin eu wisi suscipit nulla suscipit interdum. Nullam non wisi a sem suscipit semper eleifend.</p>
            <a href="#" class="button">Learn More</a>
        </div>
    </div>	<div id="portfolio" class="container">
        <div class="title">
            <h2>Vivamus fermentum nibh</h2>
            <span class="byline">Integer sit amet pede vel arcu aliquet pretium</span>
        </div>
        
        
        <div class="column2">
            
        
        
       
        
        
            <header class="title">
                
            </header>
           
        </div>
    </div>
</div>
<br /><br /><br /><br />
<div id="copyright" class="container">
    <p>&copy; . All rights reserved. | Photos by <a href="">Angelo Wallner</a> | Design by <a href="" rel="nofollow">Angelo Wallner</a>.</p>
</div>